### ISSUE TITLE
bug: pickable objects get larger when picked up

### ISSUE THREAD

**Issue by psychicgoldfish** [GodotVR/godot-xr-tools#151]
hello! I'm trying to have an object able to be picked up. I used the wiki and set it up, but realized that the automatic snapping to the pickupcenter didn't look good for it, so I turned off Reset Transform On Pickup. 
now, for some reason, when I pick up my object, it grows in size a large amount!

**Comment by Malcolmnixon** [comment]
This indicates you may have some sort of scaling being applied - either in the parent of the object being grabbed, or the pickable item, or the player. Could you check for non-uniform scaling?

**Comment by psychicgoldfish** [comment]
I think the problem is happening with this line `_remote_transform.transform = picked_up_by.global_transform.inverse() * global_transform` in _do_precise_grab().

**Comment by Malcolmnixon** [comment]
I would class this as a bug. I have to admit I've never modified world scale. Mine is always set to 1x as I noticed some oddities with the ARVR object transforms (camera and hands) when I tried turning the player into a giant or a mouse through world-scaling.

**Comment by psychicgoldfish** [comment]
should I make a new issue for it?

**Comment by Malcolmnixon** [comment]
No need, we'll track it in this ticket as it also contains the investigation.

**Comment by Malcolmnixon** [comment]
I have a fix, but I need to pass it by a few other developers. I'm having a devil of a time getting the pickup to "unwind" the scaling performed to the player. Additionally any wrist or belt snap-zones are also scaled and end up having the same problem.

My fix (with some accompanying script changes) is to create an "Unscaled" Spatial under the players controllers where scale-sensitive items can be placed.
![image](https://user-images.githubusercontent.com/1863707/175436336-07d1f640-efca-4400-a01f-a763fc09358b.png)

Both ARVRControllers have the following:
 1. A Node child called "Unscaled", and as Nodes are not Spatial, they don't inherit their parents transform/scale
 2. A Spatial child of the Node called "UnscaledContainer", and as its parent is a Node it doesn't inherit a transform/scale
 3. A RemoteTransform called "UnscaledTransform" which drives UnscaledContainer, but has update_scale disabled

The "UnscaledContainer" Spatial can then have the Function_Pickup and Snap_Zone added as children, and they will move and rotate with the hand/controller, but won't be affected by the players scale.

The script changes are necessary because many of the controller functions assume they are *DIRECT* descendants of the ARVRController nodes. Instead they need to be modified to search for an ancestor ARVRController.

**Comment by Malcolmnixon** [comment]
@BastiaanOlij decided that the actual scaling performed on the ARVRController nodes was incorrect and should be removed. This will be included in godot-openxr 1.3.0 and also requires a change to the Hand.gd script to scale the hands with the world_scale. 

These pull requests will be synchronized for release, and are available now for testing in:
 - https://github.com/GodotVR/godot-xr-tools/pull/152
 - https://github.com/GodotVR/godot_openxr/pull/215

**Comment by Malcolmnixon** [comment]
You may want to check out the latest https://github.com/Malcolmnixon/godot-xr-tools-demo which includes areas to scale up/down the player. Doing this no-longer causes held objects to rescale.
