### ISSUE TITLE
Scrolling titles on teleport get blockier after a few scene changes

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#208]
I'd say it was something wrong with the mipmaps, but this is some kind of shader, so I have no idea what could be up.
![image](https://user-images.githubusercontent.com/677254/195909685-81b0bacc-5dac-49c0-8f38-9eba6160678d.png)

**Comment by Malcolmnixon** [comment]
Fascinating. I usually run in and out of all scenes when doing a full test of changes and I don't see that quantization of the X axis.

Could it be time-related rather than the number of scene transitions? It might be an effect where TIME gets numerically large in the shader and so fine detail is lost. If so then I might need to add a modulo In at some point earlier in the time path.

**Comment by Malcolmnixon** [comment]
Could you check out the pull request and verify whether it fixes your issue. I was only able to artificially induce it on my system.
