### ISSUE TITLE
Default to snap turning, and make snap turning behave the same as in most games

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#209]
Smooth turning is pretty sick making for me (and I have a strong stomach) and very rarely found in games. 
(It's a default off in `movement_turn.tscn`, but for some reason turned on in every demo scene.)

Also, snap turning is normally implemented as one snap per joystick jerk, rather than on a timer delay basis.  If I coded this up is it likely to be pulled in?

**Comment by Malcolmnixon** [comment]
The smooth turning is alas a bias from me - I prefer smooth movement, turning, and strafing as I find it easier to move in front of the test objects.

We had a change to the turning back in https://github.com/GodotVR/godot-xr-tools/pull/97 which changed the responsiveness. I would say if you wanted to code it up, we would want to have a drop-down of different styles - smooth, snap, or snap-repeat.

**Comment by BastiaanOlij** [comment]
Hmmm, interesting... I agree with @goatchurchprime , snap turning should be the default, smooth turning should be something people opt-into.

Almost all of us veterans forgo snap turning. Worse yet, I turn it off because I always get complaints on my tutorials, when people see the snap turning they think things are running at 2fps and I got tired of explaining why snap turning exists for VR games :)

But I think it is important to keep it on for default so if we changed that at some point, I do think we should change that back.

**Comment by Malcolmnixon** [comment]
Turn movement is set for snap-turn by default, and the teleport demo shows off snap-turning.

Many of the other demos are trying to show off physics-related movement which is already for people with VR legs.

We could put snap-turn on for some of the other scenes, or we could have a global options setting in the main-menu scene.

**Comment by BastiaanOlij** [comment]
With #229 you can now set the behavior you want in the startup window and it will save it as a user preference. 
For your own projects you can set the default setting for new users in project settings or you can ignore the new settings system and override it
