### ISSUE TITLE
movement_climb should be one-handed

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#210]
The two handed average offset is something I've never seen in any game, partly because it will always jerk when the second hand is applied or released.  Normally the second hand takes control from the first hand.  

Also it would be feel more positive if the hand/arm had to be within the surface rather than an invisible distance from away.

**Comment by Malcolmnixon** [comment]
We could change it to use the most recent grab possibly. The averaging solves some corner case - for example with single-handed grabbing what happens when:
 1. The player grabs a wall with the left hand.
 2. The player grabs the wall with the right hand and pulls themselves up a foot.
 3. The player let's go with their right hand, but is still holding with the left.

**Comment by BastiaanOlij** [comment]
It's also a matter that we don't anchor the hands, they stay attached to the controller. 

Many climbing games do have two handed functionality but the moment a hand grabs something, it is no longer attached to the controller, it is now attached to the place that is grabbed, and is let go automatically when the hand moves too far away.

That said, @goatchurchprime example is also true, where the last hand that grabs determined the movement. Let go with that hand and the first hand takes over again.  Still even in that situation the hands once grabbing the wall get anchored to that place on the wall instead of following controller movement.

**Comment by Malcolmnixon** [comment]
I'm reminded of a Population-one bug where a player could hold on to a wall, then run half way across the map, then I believe if they released the grip they would teleport back to the wall.

We almost certainly have a similar bug in our current implementation. If a player grabs a stationary wall with the left hand, and a climbable moving platform with their right, then they would almost certainly be carried along at the average/center of those two positions.

One-handed with "snap the grab" if too far would solve that, although as you say we want to solve the hand decoupling at the same time.

**Comment by BastiaanOlij** [comment]
I still need to play Population One...

**Comment by Malcolmnixon** [comment]
@goatchurchprime could you confirm this climbing behavior works as desired, and if so close the issue.
