### ISSUE TITLE
Feature request: Default compatible hands and animation tree for all the controller buttons

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#270]
It would be nice to bind in an animated left hand mesh into this scene that was exactly aligned to be holding the controller.  (You could make it invisible when you didn't need it.)  

![image](https://user-images.githubusercontent.com/677254/202166505-1327152a-d3f8-472f-9cb9-b28c8ece712b.png)

It should also include an animation tree for each mesh (the controller buttons, and the fingers moving and pressing the buttons) in order to replicate the Quest home room.  

The reason this is useful is that when I pass the controllers to a VR novice after putting the headset onto them, they don't know where their hands are in relation to this weird/unfamiliar shaped object they've now got in their hands.  They have no idea where their fingers are.

Also, this could help facilitate those on-boarding animations you get in some games where they show the controller in front view with the relevant button highlighted and your thumb or finger slowly and repeatedly moving across to press it.

**Comment by DigitalN8m4r3** [comment]
not sure about capturing the thumb, the current blendtree and the actual System in place in godot xr is only working with Index Finger and the Rest of the fingers bend on the grip


This means that the thumb would need to be seperated function wise to allow for that or that there should be a check on the controller Buttons around the thumb area that changge its pose when your touching the Button and pressing down

Not sure what might be the better way

**Comment by DigitalN8m4r3** [comment]
before BastiaanOlij came up with the handpose stuff i was working on using soley the animationtree to perform handposes on different animation/blendtree values = it resulted in a dead end because i simply wasnt able to code the neccessary stuf in and i didnt received positive feedback to contine this and with that being said

splitting the blendtree to have all fingers accounteed for is what you seem to want with the above but that will involve the blessing by @BastiaanOlij and its something you should talk with him about and explain the pros for your request because only doing this to perform what oculus is doin it in their home screen is not a reason to do this and it will involve alot more because you will need a way to move the fingers animation/handposewise as well and not only with handtracking

**Comment by BastiaanOlij** [comment]
If someone wants to work on this I'd applaud it but I want to caution everyone that this task is near impossible.

OpenXR does not give us reliable information about the controller that is used, and the collection of models and hand poses that would need to be maintained to support this cross platform is immense (not to mention potentially copyrighted as we're dealing with vendors IP here).

We won't be accepting solutions into XR tools that only work for one headset, or one vendor, the whole promise of XR tools is that it would be a toolset that works regardless of a particular ecosystem. If a solution only works for one platform, it belongs in a plugin specific for that platform, not in a generic plugin. Obviously such a plugin could be an extension on XR tools which is fine (say you wanted to do this for just Meta Quest seeing its the most popular consumer platform at this moment in time).

For XR Tools, there is also a maintenance issue as newer headsets come on the market and XR Tools suddenly has a mandate to try and keep up.

That all said, OpenXR itself holds the promise that at some point the APIs for this will be available and this becomes a non-issue. The hand tracking API already supports proper positioning of fingers conforming to the controller being held and Valve has implemented this, other vendors are encouraged to do so as well so hopefully this will happen.
What is still missing is being able to obtain the correct controller mesh, though again with Valve those are obtainable, just not positioned correctly (as OpenVR had full support for all this and all meshes are stored in the SteamVR resources folder), and there is every reason to believe this will be properly supported in OpenXR at some point in time.

There is a real risk here that we move mountains, only to find out the functionality suddenly comes gift wrapped in OpenXR and in such a way that it's better then we could ever do it as vendors will be supplying proper meshes and finger positions for their hardware as part of their drivers/runtimes.

Until then my advise to anyone (and even beyond that) is to forego displaying controllers and making your game design such that this is not needed, if it is already impossible to display the correct controller model because you don't know what the player is holding in their hands, it's already immersion breaking.

This was the whole idea behind the hands in XR tools to begin with, to create something agnostic of the XR platform the user is using and instead concentrate on something that makes sense within the virtual world you are creating. This is where I think @DigitalN8m4r3 and @Malcolmnixon work has been so excellent now having a system where hand poses are automatically selected based on in game context, the object you're about to grab, the object you're about to interact with, etc.

Anyway, that's my 2 cents on the subject :)

**Comment by DigitalN8m4r3** [comment]
as i talked with julian about requirements for the handtracking to work as this is the motivation behind the above (at lest i suspect it that way), i started remaking all animation handposes on a skeltal armature that got bone roll of 0 set to all bones, julian already tested the handtracking code he got with a wip version of my reworked hands and its working more or less pretty decent from what he showed me picturewise

now with that being said, i share the pov of @BastiaanOlij and as i mentioned to @goatchurchprime
am not seeing handtracking a priority as there is alot more that needs to be accounted for and some of those systems arent even merged yet such as the multiple grabpoints and the are handpose stuff and others arent even started such as twohanded pickables

for example what todo when using handtracking on a pickable with multiple grabpoints - handposes setup,
the code needs to be adjusted for along with alot more and honestly i dont see why @Malcolmnixon should carry the weight of adjusting all of this and therefore if @goatchurchprime wants to get this stuff implemented, am expecting him to do the necceserry changes on its own and do a proper pull request and then am gonna submit my reworked hands that work with his handtracking code

**Comment by goatchurchprime** [comment]
Some of @BastiaanOlij's concerns about all the different hardware are foreshadowed in the OpenXR spec: there's an MSFT extension (what's it stand for?) that has functions for importing a controller and hand-mesh model through the API:
  https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_MSFT_controller_model

Even if it's not in the library, developers are going to need this feature for their target platform today, so ensuring that that the toolkit is compatible with how they are likely to do it is a good idea -- even if the feature is not included.

So, as an idea, I think this could be done with a set of synthetic hand positions based on one fixed handle grip pose, and then some simple IK positions for the thumb to reach various XYZ places on the controller face.  This generates a joint_positions[] array, which is then mapped to the hand skeleton as though it were read from the hand-tracking API.  Then, in future when I assume each system would generate finger positions for its own controller after implementing the MSFT_controller_model feature, this approach would be compatible.  

In light of this, I'm still in two minds about the current FPController structure where we have different child nodes for controller-tracking and hand-tracking, and one of them has to be disabled when the other one is active as you switch between controllers and hand tracking, and everything that depends on these two modes has to check both nodes.

From the point of view of this feature, we could say there is always a hand mesh, and sometimes it is holding a controller, and sometimes it is not.  But this is just an animated object in your hand combined with some sort of holding pose.  Then if we substitute in a different library of hand-tracked poses (where, for example, pulling the trigger and grip buttons together maps to a joint_positions array for a fist), and set the controller to invisible, we get back to the conventional default situation that we now have implemented.

**Comment by BastiaanOlij** [comment]
MSFT is a Microsoft vendor extension and so far there has been little adoption of it by the other vendors.

And I agree that people don't just need it today, they need it yesterday, but there is nothing in the current API that helps us here. Like I said, there is no way to query with certainty which controller is being held, and there is no way to get the full state of the controller. I'm also not happy with the current approach in OpenXR that made us having to do the split implementation but for Godot 3 we're stuck with that.

I know whats coming, I can't say anything more about it, but trust me when I say that any time spend on this right now is time wasted. By the time we've implemented all this we'll have a half functional solution with a lot of compromises, and we can start again from scratch.

Best to wait until OpenXR matures on this front.

**Comment by BastiaanOlij** [comment]
That all said, dynamics idea to just have a generic controller and a hand pose that fits sounds good.
And for those who simply target Quest, Using one of the Quest controllers and having a hand pose that fits around that properly would be a nice thing to just have available (though again I don't believe it belongs in the XR tools library, it should be something separate, just assets you can download and use with the XR tools library). 

Sadly there is no way to know with certainty whether the player is holding a Quest 1, Quest 2 or Quest pro controller, and all 3 need different poses, and those are the easy ones.

**Comment by goatchurchprime** [comment]
For the record, in my TunnelVR app I've used a Quest1 controller model with a material override to turn them white, and nobody has ever noticed.  

Originally I did it all with hands that animated, like in the xr-toolkit, but this made on-boarding extremely difficult because people had no idea what buttons they were supposed to press or what the hand poses meant, so I was forced to show the controllers.

The next iteration was to colour the buttons Orange and Green because nobody knew what "Grip" and "Trigger" meant, and now I could tell them to hold the green button in instead of the grip button.  

It then became necessary to animate the buttons because of the number of people who would hold the shaft of the controller without putting their finger on the trigger, and this was a good way to tell.

So what I'm trying to say is my primary motivation for this feature is to help novice users find their way round these unfamiliar devices (controllers) by touch, when they've probably never seen them before, and now they're in the dark with a headset on.  It succeeds if it reduces the level of frustration when trying to remember and find the controls.

![image](https://user-images.githubusercontent.com/677254/202482539-9ea4d656-5671-461c-9611-647245f0519d.png)

**Comment by BastiaanOlij** [comment]
Not being noticed is not the same as actually doing something that is allowed. Meta has no issues for you using their controller models when you're publishing games for their hardware, they might be a little less happy if you make a very successful game using their controller models on say SteamVR. I really really doubt it though however there still is a big difference between us saying it'll probably be ok, and us actively promoting the use of models with potential IP infringement.

Again, I am 100% in agreement with you that this functionality is important and it's a message I'm actively giving within the OpenXR groups.

I'm just very aware that what is required to do this properly, especially considering that we're not all using Quests, would be a lot of work while still remaining compromised because we're simply not getting the right data. For instance, for any controller that is not specifically part of the current OpenXR spec, we're not getting any information. For any developer using the WMR ecosystem, we're just being told "it's a WMR controller" and while many come with the same controllers, some have very different controllers.

Finally, while we map every button 1:1 to actions in Godot 3, this is not how we're supposed to use the action system and in Godot 4 we now have a proper implementation for this. This allows the developer to create actions meaningful to how their game works without consideration how those actions are mapped to controller inputs, especially as the long term plan here is for XR runtimes to give users control over these mappings.

So you may have an action called "Open menu" in your action map, and you may have that bound by default to your A button on your quest controller. There is no guarantee it is actually bound to the A button on whatever controller the player is using, they may not even have a controller with an A button, and *currently* there is no way for you to know. 

The OpenXR working group is aware of this, we're not the only ones who are running into this gap in the OpenXR spec, especially because Valve had all this stuff completely implemented in OpenVR, obtaining the correct render model, retrospective APIs to let you know where the buttons are and how they're mapped (even if the user overruled your default mappings), etc. But it is still being worked on for OpenXR.

Again, I can't stress this enough, it would be amazing if someone as an intermediate solution would take a few quest controller models, put them in an asset, add all the code that will show the correct finger poses based on the inputs we do receive and provide a solution that right now would be useful for the majority of developers even if you're showing the wrong controller models. But i don't believe that solution belongs in XR tools.

**Comment by BastiaanOlij** [comment]
We're closing this issue because this is not something solvable in XR Tools. We do not get enough platform information and as I already mentioned above, the amount of meta data to maintain is stagering and will often be wrong.

Good case in point, we don't get told which Touch controller a user is holding, if we're told they are holding a Touch controller it can be any of the following scenarios:
- It could be an origin Rift Touch controller
- It could be a Rift S touch controller
- It could be a Q1 touch controller
- It could be a Q2 touch controller
- It could be a Quest Pro touch controller
- It could be another controller from another brand that is mimicking a touch controller

So positioning the fingers properly in combination with showing the correct controller is not possible.

In the (near) future OpenXR will likely provide features for this and you will be able to add support for that by the logic added upstream in Godot itself, however for XR Tools we're still hamstrung as we need a solution that is cross platform and works outside of OpenXR as well.
