### ISSUE TITLE
Fix the warning on the Function_Teleport node

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot-xr-tools#29]
It's listed as something to do in the instructions, but here is a reminder.
   https://github.com/GodotVR/godot-xr-tools/wiki/Teleport

It seems that you need the KinematicBody so you can access `get_world().get_direct_space_state()` which you need to execute `intersect_ray()` or `collide_shape()`.  

The KinematicBody is not happy unless it contains a CollisionShape (which is why there is a warning).  Now you create a CapsuleShape collision shape in the `_ready()` of the Function_Teleport.gd, so why simply put a CapsuleShape into the KinematicBody and use that in your `collide_shape()` function call?  

I've tried this (in a function which is supposed to create and place objects where you are pointing, instead of teleporting) and there seems to be a problem: when you set the global_transform on the CollisionShape, it seems to set the global_transform on the KinematicBody whether you like it or not!  Is this something you have encountered, which would explain why you needed to make a local collision shape to use in the `collide_shape()` function?

**Comment by BastiaanOlij** [comment]
I guess we could do this because as long as move and slide is not executed and the capsule shape doesn't interact with anything it could be created as such.

That said, what I really wanted to do is change the root to a Node, in Godot 3.2 it should now be possible to get the world without needing a kinematic body, I need to find some time to test that

**Comment by BastiaanOlij** [comment]
Added the workaround and works like a charm, thanks for the suggestion @goatchurchprime
