### ISSUE TITLE
Prevent snap zones from allowing objects to "fall" into place

### ISSUE THREAD

**Issue by dsnopek** [GodotVR/godot-xr-tools#311]
Currently, pickable objects can fall (or be thrown) into a snap zone, which isn't always desirable. It looks pretty funny with the teacups in the pickable demo:

![xrtools-drop-teacup](https://user-images.githubusercontent.com/191561/210191574-14b60a98-7bc1-45d3-a084-28dbee1ca8d5.gif)

It'd be great to have a mode for snap zones that required the object to be placed directly in the snap zone!

I've been struggling with how to implement this, though. My first idea was to have the snap zone connect to the "dropped" signal on any pickable objects that enter, but that clashes with the pickable objects clearing out their collision layers when being held (at least by default).

Any ideas?

**Comment by Malcolmnixon** [comment]
It's actually one part of a two-part problem which includes the initial snapped state on scene loading. The current approach is to position objects in the snap zones and hope they get proximity-snapped when the scene loads. That works for desktop, but it turns out running the demo scene above native on a quest doesn't correctly snap and the teacup falls on the table.

So the two parts to this are:
 - Support snap modes of [OnEnter, OnDrop]
 - Support NodePath for snap-on-load

The OnDrop may be something we can do with the XRToolsFunctionPickup as it maintains a list of all pickable objects in range and the snap zones are pickable (so you can grab items from them).

Essentially when the XRToolsFunctionPickup drops an object it could search its list of pickup areas for anyone with an on_dropped_near method and let them grab it.

**Comment by dsnopek** [comment]
> The OnDrop may be something we can do with the XRToolsFunctionPickup as it maintains a list of all pickable objects in range and the snap zones are pickable (so you can grab items from them).
>
> Essentially when the XRToolsFunctionPickup drops an object it could search its list of pickup areas for anyone with an on_dropped_near method and let them grab it.

Aha! This sounds way better than any of the things I've been trying so far :-)

**Comment by Malcolmnixon** [comment]
Another thought on detecting pickables dropped in snap zones is that the snap zones could subscribe to the pickables "dropped" signal when the pickable enters the snap zones area, and unsubscribes when it leaves.

**Comment by BastiaanOlij** [comment]
Resolved by #319.
