### ISSUE TITLE
Doesn't work with Godot Beta 16

### ISSUE THREAD

**Issue by Eisenspalter** [GodotVR/godot-xr-tools#350]
I tried it with Godot Beta 16. 
![image](https://user-images.githubusercontent.com/4734410/215276685-f432a9f8-47b5-480f-a322-6611ecdbf8af.png)

**Comment by Malcolmnixon** [comment]
You may wish to try the 4.0-dev branch. Fixes for beta-16 were checked in yesterday.

**Comment by Eisenspalter** [comment]
I used the 4.0-dev branch

**Comment by morekitsch** [comment]
I get the same error. It happens when you try to move from the 'staging scene' to one of the other scenes after you hold the trigger. Fresh download from 4.0-dev 10am PST

**Comment by Malcolmnixon** [comment]
It appears to be a bug in Beta-16 - other people are chatting about identical problems in the gdscript developer channel. No matter how many times the project is re-loaded, the DemoSceneBase class in `/scenes/demo_scene_base.gd` isn't recognized as a class. The fix is to edit the file (add then remove a space) then save the file; and then after a few seconds Godot recognizes it.

**Comment by BastiaanOlij** [comment]
I think its some sort of optimisation to prevent reparsing the script repeatedly because it fails to parse. The assumption was probably that if the file isn't modified, its not worth parsing it again because it leads to the same error. But that is a very optimistic view as a script could fail to parse based on a dependency. 

Anyway, that is my theory, I could be totally wrong :)

**Comment by pietru2004** [comment]
I seen that project settings can't be opened

**Comment by Malcolmnixon** [comment]
This is the official bug in godot - https://github.com/godotengine/godot/issues/72154

**Comment by BastiaanOlij** [comment]
This should be resolved as mentioned in the bug report Malcolm referenced. Closing this issue.
