### ISSUE TITLE
Scene switcher needs to support multiple player entry locations

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#369]
Currently a scene has a single starting location where the ARVROrigin node is located; however most games allow the player to re-enter a scene from different points. Switching scenes should support providing an additional "starting-point" identifier.

**Comment by DigitalN8m4r3** [comment]
hmm indeed this should maybe ideally be tied to some kind of save checkpoint and should allow for carrying items as well because makin this available without keeping that in mind just makes things harder afterwards.
Would suggest a new demo scene that enables the player to enter/reEnter from different locations and to carry over items, ideally using some kind of inventory.
So if this is what you got in mind as well, i would work on the inventory demo scene and you could fuse in the starting/reEnter and carry over part?...

**Comment by BastiaanOlij** [comment]
We also need to add a mechanism to player_body so it can tell the situation of moving to a new location and teleporting/starting at a new location as currently the kinematic body may try to move from the starting location to the location of the player, and fail if there is a wall in between.

**Comment by Malcolmnixon** [comment]
Pull Request #508 adds a `player_teleported` signal on the XRToolsPlayerBody.
Pull Request #509 adds support for overriding the spawn-position of the player when switching scenes.

**Comment by BastiaanOlij** [comment]
This is now implemented, see https://github.com/godotvr/godot-xr-template for an example of this.
