### ISSUE TITLE
The keyboard should support input with 2 hands (pointers).

### ISSUE THREAD

**Issue by Eisenspalter** [GodotVR/godot-xr-tools#376]
The keyboard should support input with 2 hands (pointers).

**Comment by Malcolmnixon** [comment]
Pull Request #496 includes adding poke objects to both hands, so it's possible to touch the keyboard with either hand.

It's also possible to directly add FunctionPointer objects to each hand and trigger the keyboard by pointers on either hand; however that's not quite as nice due to the pointers behaving like mice, and godot doesn't support multiple mice.

**Comment by Malcolmnixon** [comment]
Pull request #507 adds support for multitouch and changes the keyboard to use multitouch controls. With this it's possible to type with 2 hands as pointers, or 2 hands as fingers poking at the keys

**Comment by BastiaanOlij** [comment]
Closing this as it's implemented.
