### ISSUE TITLE
BeltsnapZones - rotate along the hand movement

### ISSUE THREAD

**Issue by DigitalN8m4r3** [GodotVR/godot-xr-tools#403]
Issue:
Beltsnapzones inside the Playerbody are not behaving correctly
they swing along the arm forward/backward movement, to be more precise they actually rotate along and this is no behaviour we would want inside a beltsnapzone

**Comment by Malcolmnixon** [comment]
The BeltSnapZone is directly tied to the body, so the problem is the rotation of the body.

### Current Approach
The current implementation blends two direction-sources to select the body forward direction:
 1. The direction the camera is facing
 2. The left-hand-to-right-hand vector (rotated 90 degrees to point forwards)

The problem with this approach is that the hands may be busy manipulating objects, and when the hands are close their associated vector isn't a good indication of body direction.

### Proposal
I would suggest a slight modification to the body forward direction - three contributors:
1. The same camera-forwards direction - flattened horizontally and normalized to have a contribution of 1.0
2. A vector from the body to the average position of the hands - flattened horizontally but not normalized
4. The left-hand-to-right-hand vector rotated forwards - flattened horizontally but not normalized
These three sources would have scale coefficients applied, then summed and normalized to make a single forwards direction.

The second vector (from the body to the average position of the hands) attempts to deduce the direction the hands are pointing. If the hands are pointing in the same direction and are away from the body, then the resultant vector will increase in magnitude and have an increased contribution to the resultant direction. This should probably be scaled up slightly as the average forearm rest length would be less than 1 meter.

The third vector (from left to right hand then rotated forwards) attempts to deduce the players direction when they are T-Posing. When the hands are further apart, the resultant vector will increase in magnitude and have an increased contribution to the resultant direction. This should probably be scaled down slightly as the average T-Pose hand-distance would be longer than 1 meter.

A first guess at the contributing vector scaling based on average human geometry would be:
 - Camera * 1.0 (normal length)
 - Hand-average * 2.5 (roughly normalizes for forearm length)
 - Hand-distance * 0.7 (roughly normalizes for t-pose length)

**Comment by BastiaanOlij** [comment]
Figuring out which way we're facing is an impossible task that will always be flawed until we get reliable body tracking (and even then we need a fallback in case the user doesn't have the required functionality). We simply don't get enough data.

There is a body tracking extension that Meta added to OpenXR that is seeing some adoption, and we have our current body trackers through poses if you're using HTC trackers or other full body tracking systems. We'll need to think about how we deal with those optional features in XR Tools.
