### ISSUE TITLE
[Godot 4.0, godot xr-tools 4.0.0, Meta Quest 2] Godot-XR-Tools Black Screen After Pressed Trigger Button

### ISSUE THREAD

**Issue by arisvaldez** [GodotVR/godot-xr-tools#415]
Hello everyone.

when I run the demo from Godot's Editor using play button, this work fine in Oculus Meta Quest 2, (Except the Joy Axis, the player don't move) i can see all, the world, map, teleports, etc.

but when I run the demo from the Meta Quest 2, after Pressed the trigger button on loading screen, the game don't load the next Screne, only show a black screen. 

this only happen in the latest version 4.0, in the previous beta version , work fine (Except the climb, it's buggy)

**Comment by Malcolmnixon** [comment]
It seems to be a scene loading problem - there's a chain of errors reported through remote debugging:
 - E 0:00:02:0289   _load_data: Unable to open file: res://.godot/imported/SkyOnlyHDRI023_2K-TONEMAPPED.jpg-bcb5464e5ed42ee2463b71652f907f38.bptc.ctex.
 - E 0:00:02:0290   _load: Failed loading resource: res://.godot/imported/SkyOnlyHDRI023_2K-TONEMAPPED.jpg-bcb5464e5ed42ee2463b71652f907f38.bptc.ctex. Make sure resources have been imported by opening the project in the editor at least once.
 - E 0:00:02:0290   _load: Failed loading resource: res://assets/ambientcg.com/SkyOnlyHDRI023_2K-TONEMAPPED.jpg. Make sure resources have been imported by opening the project in the editor at least once.
 - E 0:00:02:0290   load: Can't load dependency: res://assets/ambientcg.com/SkyOnlyHDRI023_2K-TONEMAPPED.jpg.
 - E 0:00:02:0290   _load: Failed loading resource: res://.godot/exported/133200997/export-7cf3fd67ad9f55210191d77b582b8209-default_env.res. Make sure resources have been imported by opening the project in the editor at least once.
 - E 0:00:02:0290   load: Can't load dependency: res://default_env.tres.
 - E 0:00:02:0290   _load: Failed loading resource: res://.godot/exported/133200997/export-e6ab060a29b7c2a8e86205a7dbbb11a2-scene_base.scn. Make sure resources have been imported by opening the project in the editor at least once.
 - E 0:00:02:0290   load: Can't load dependency: res://addons/godot-xr-tools/staging/scene_base.tscn.
E 0:00:02:0290   _load: Failed loading resource: res://.godot/exported/133200997/export-f06392e81065813437459a414c02143a-main_menu_level.scn. Make sure resources have been imported by opening the project in the editor at least once.

What I'm seeing is that the failure is triggered due to a missing ` .godot/imported/SkyOnlyHDRI023_2K-TONEMAPPED.jpg-bcb5464e5ed42ee2463b71652f907f38.bptc.ctex` however when I tear apart the APK file I find `.godot/imported/SkyOnlyHDRI023_2K-TONEMAPPED.jpg-bcb5464e5ed42ee2463b71652f907f38.astc.ctex`. Note that it's expecting 'bptc' but has a file with 'astc'.

The project has two texture formats enabled:
 - Rendering / Textures / Import S3TC BPTC = ON
 - Rendering / Textures / Import ETC2 ASTC = ON

The .import file mentions both formats:
 - "imported_formats": ["s3tc_bptc", "etc2_astc"],
 - path.bptc="res://.godot/imported/SkyOnlyHDRI023_2K-TONEMAPPED.jpg-bcb5464e5ed42ee2463b71652f907f38.bptc.ctex"
 - path.astc="res://.godot/imported/SkyOnlyHDRI023_2K-TONEMAPPED.jpg-bcb5464e5ed42ee2463b71652f907f38.astc.ctex"

The Quest Pro export has the following default features - android, arm64, arm64-v8a, astc, etc2, mobile

So the question is why Godot decided to try and load the BPTC version when the project was explicitly exported and bundle with the ASTC version.

**Comment by Malcolmnixon** [comment]
It's possibly the same issue as https://github.com/godotengine/godot/issues/74348

**Comment by Malcolmnixon** [comment]
As a temporary workaround, try adding 's3tc' and 'bptc' to the quest features list in the export. That worked for me by bundling the unwanted PC textures in with the APK - it will be much larger than needed.

**Comment by Malcolmnixon** [comment]
This issue is now being tracked in the main Godot project - https://github.com/godotengine/godot/issues/74451

**Comment by Malcolmnixon** [comment]
This should now be fixed in the [4.0.2 RC 1](https://godotengine.org/article/release-candidate-godot-4-0-2-rc-1/) build. Could you confirm this fixes your issue.

**Comment by BastiaanOlij** [comment]
As far as we are aware this was fixed some time ago in upstream Godot. Closing.
