### ISSUE TITLE
Where is the assign ?

### ISSUE THREAD

**Issue by BracerJack** [GodotVR/godot-xr-tools#48]
![bbbbb](https://user-images.githubusercontent.com/46036208/125417564-4b127406-b0f5-4427-878c-9466b0372ec4.png)

**Comment by BracerJack** [comment]
![VR Question](https://user-images.githubusercontent.com/46036208/126075142-bbcf4640-8b78-4b1a-9f27-420a1c794506.png)

**Comment by BracerJack** [comment]
To everyone else reading this:
Due to lack of respond from the creator of "Godot XR Tools", I have moved on and am currently using "VR Tools" and it works great right out of the box, and I don't even have to deal with setting the collision layers/masks like I have to with "Godot XR Tools", everything just works right out of the box [Arc Navigation/Pickable RigidBody/UI Interaction, WOW !] and I can now get back to my game logic and 3D modeling.

**Comment by BastiaanOlij** [comment]
Hey @BracerJack ,

Which is the VR tools you are talking about? Feel free to post a link, choice is good. 

Couple of things just in case you're still interested and for anyone else who may run into the same issues.

`function_pointer` is a function that adds a laser pointer to your player so you can interact with a UI. It does not need to know about the camera so I'm not sure why you are expecting it to ask for one. You can find a little bit more information about it here: https://github.com/GodotVR/godot-xr-tools/wiki/PointerAndUI

The teleport function needs to know about the camera because it moves the player and therefor needs to know the location of the player. The ARVROrigin point only reflects the center of your tracking space and a player can walk away from it. 

Most of the functions in the toolkit should now have the correct default layers but it is something you want to be able to override as a game builder. 
As a tool builder I can't force you to use my layer setup onto game designers, if they have more complex games they may have very good reasons to assign their own layers.

**Comment by Noobidoo** [comment]
I'm not sure but i think he's talking about https://github.com/anunknowperson/godot-vr-tools.
It has some neat ideas and features but looks less configurable.
His for example uses groups to determine if a object is grabbable.
Also an improvement I might test out for this is to not use the eular angle but a quat.

**Comment by Malcolmnixon** [comment]
Is anyone having issues with Function_Pointer configuration? If not I'm going to suggest closing the issue.

**Comment by Henodude** [comment]
I suggest closing this issue, as it has not had any activity for almost a year.
