### ISSUE TITLE
HTC focus 3 unusable visuals...

### ISSUE THREAD

**Issue by TrevorBlythe** [GodotVR/godot-xr-tools#588]
![Screenshot_20231213_164705](https://github.com/GodotVR/godot-xr-tools/assets/77030926/8607e10d-4e65-4e96-8fbc-708180f66fb5)

This is what im seeing on the htc vive 3.

Im on a fresh ubuntu install. Using godot 4.1, and the 4.1 release of godot xr tools. Im using compatibility renderer and that godot openxr loaders addon.

Any clue what this is?? 

Im on godot 4.1 and here are my settings.
![Screenshot from 2024-01-08 16-54-03](https://github.com/GodotVR/godot-xr-tools/assets/77030926/a6c3e32f-be84-4a16-a97a-882f3c939c04)
![Screenshot from 2024-01-08 16-54-15](https://github.com/GodotVR/godot-xr-tools/assets/77030926/ff821363-f540-490e-8cd3-5ae0d26ab359)
![Screenshot from 2024-01-08 16-54-24](https://github.com/GodotVR/godot-xr-tools/assets/77030926/536b2788-66bd-456c-b5c4-53e9e6983212)

**Comment by TrevorBlythe** [comment]
You can still make out shapes of objects and move around and interact. Just that the screen is all messed up. Works perfectly on quest 2.

**Comment by BastiaanOlij** [comment]
Hey @TrevorBlythe ,

Sorry for the late response on this. This is an issue with the wrong sample count used on HTC devices and should be fixed with the latest version of Godot. We recommend you update to 4.2.1.

Also we recommend you use the compatibility renderer for now. Make sure to check this in your project settings and make sure this is set properly for both desktop and mobile configurations.

**Comment by TrevorBlythe** [comment]
its okay and your right that works.
