### ISSUE TITLE
Flight movement needs more advanced features

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-xr-tools#80]
The current flight control is implemented as a secondary feature of Function_Direct_movement which prevents adjusting/separating the order of walking and flying controls.

Additionally flight deserves some advanced features, such as:
 - Acceleration, thrust, gravity, and inertia
 - Thrust strength based on joystick (E.G. trigger) feedback

**Comment by BastiaanOlij** [comment]
I wonder if we can do steering based on looking direction. If we take the current velocity vector and compare that to the forward look vector, we can use the angle as a steer input.

**Comment by Malcolmnixon** [comment]
My initial glide-movement used that approach, but I switched to determining a "forwards" direction based on the t-pose of the controllers because the player couldn't look around without changing course.

Both approaches (head or t-pose) may be appropriate for different games, so this would probably just be a configuration option.

**Comment by CigamPower** [comment]
For me it would be interesting to have it as a separate mode of movement, so I can be either walking or flying.

Personally I prefer controller orientation for choosing the angle, but some people prefer head. It would also be nice to be optional.

There are a lot of aspects like that as an option or toggle would make it easy. Not just for flying. Since they are somewhat related here is some of a list of options that I am meaning:

Move:
- Ground Speed
- Fly Speed
- Strafe Speed
- Option for rotation or strafe on left/right
- Maybe option for rotation and strafe at the same time?

Rotation:
- Option for smooth or segment
- Speed on smooth
- Increment angle of segment

Speed:
- Cumulative? meaning if you do forward on left controller and right controller that it would be double or higher speed?

Fly:
- Orientation as head or controller
- Hold Fly mode, like it is now with grip and trigger (or some input combo)
- Toggle Fly mode, once, active you just need the joystick, and dont need to hold the grip, just a push button or something to turn it on and off.
- Glide mode, like you have in the demo.
- Elevator mode, where you can pick a vertical height, but then you walk around as if you were on a ground plane. Might could do this via one controller up and down joystick is vertical, left and right is strafe. While other controller is move and turn? not sure.
- Jetpack mode

Vignette:
- Toggle on and off
- Option whether its on all the time or based on speed
- Radius amount
- Gradient amount
- Activate speed
- Fade speed

The biggest thing I want to be able to do is easily switch between walking and flying, probably a toggle mode. And be able to turn and strafe while flying. 

A different example is in walkabout mini golf where you have to aim the controller up then press the joystick up and you will activate fly mode after a second or so. The problem with that method is it takes time to initialize, but it works well for that game since you are limited to one controller, and that was a way to not use up a separate button.

Cheers

**Comment by Malcolmnixon** [comment]
The flying mechanism seems to work well. Future flight enhancements will be tracked in their own issues.
