### ISSUE TITLE
XR Button Node

### ISSUE THREAD

**Issue by pietru2004** [GodotVR/godot-xr-tools#92]
If it is possible I would like to suggest adding of XR Button Tool.

I am still learning to code better but I have made simple button code as an example. It works using detection of player Function_pickup node. This concept could be extended to other types of buttons(levers, physic buttons and etc).
`
extends Area
class_name XRButton

# Called when the node enters the scene tree for the first time.
func _ready():
	connect("area_entered",self,"it_enter")
	connect("area_exited",self,"it_leave")

export var interact_range := 0.1

var last_hand : ARVRController = null

signal pressed(hand)
signal depressed(hand)

var menu_btn_state = 0
func _process(_delta):
	if is_instance_valid(last_hand):
		if global_transform.origin.distance_to(last_hand.global_transform.origin)<=interact_range:
			if menu_btn_state!=last_hand.is_button_pressed(15):
				if menu_btn_state==0:
					emit_signal("pressed",last_hand)
				elif menu_btn_state==1:
					emit_signal("depressed",last_hand)
			menu_btn_state = last_hand.is_button_pressed(15)

func it_enter(body):
	print(body)
	if body is Function_Pickup:
		if body.get_parent() is ARVRController:
			last_hand=body.get_parent()

func it_leave(body):
	if body==last_hand:
		last_hand=null
`

**Comment by Malcolmnixon** [comment]
There are new interactable objects under development in https://github.com/Malcolmnixon/godot-xr-tools-interactables which include:
- Area Button (triggered when an area such as the players hand/finger enters the sense area)
- Hinges (controlled by the player grabbing a handle)
- Sliders (controlled by the player grabbing a handle)

The button is still a work in progress due to work being done on the hands to include areas and/or colliders, but the demo works with a test collider added to the left-hand index finger. You may want to see if this matches what you were thinking of.

**Comment by pietru2004** [comment]
SO basicly the thing I was thinging is not there just might be in development ? Well that makes it easier :)

**Comment by pietru2004** [comment]
I would say that is what I was looking for...

**Comment by Malcolmnixon** [comment]
The area button is slightly different than your approach - it uses an area (attached to the index finger) to trigger its effect, where-as you're using a proximity and a controller button. I like that idea, so I'll look to adding that type of interactable option as well.

**Comment by pietru2004** [comment]
Well that was my best and first thought for making btn... Now...Is it ready to be used in game - I want to make a vehicle but it would be kinda hard to steer it without proper controls (+ Levers could have mode to move on collision)

**Comment by Malcolmnixon** [comment]
The wheel in the example could be used to implement a vehicle steering-wheel, and you could use a lever (with snapping) as a gear shift, but you would probably need to work out an equivalent for the gas-pedal. You could use the trigger buttons of the controllers.

Having levers react to collisions is a little more challenging. The interactable work is based on some work I was doing for doors - https://github.com/Malcolmnixon/godot-xr-doors - but it turns out using the Godot physics engine for collisions results in the levers or doors being pushed out of joint even when using a custom _integrate_forces system. It's possible to lock the joints, but that wouldn't work for a moving platform like a vehicle because the joint gets locked in "global" coordinate space.

The only option we could think of for supporting physics bodies hitting interactable sliders/joints was to have a custom handler for colliders, but that would result in a significant amount of physics work being done in GDScript and the performance may suffer.

**Comment by pietru2004** [comment]
I am making a airship(at least a prototype) - as main map. Is there any simple wiki page how to implement those levers into existing project? I try to look into demo, but it is kinda hard to understand how does "XRTInteractableSlider" get all handles without having defined "grabbed_handles" var in script

**Comment by Malcolmnixon** [comment]
Unfortunately there's no official documentation at the moment. You may want to review the Slider scene:
![image](https://user-images.githubusercontent.com/1863707/156896065-b989f3f7-dc02-42c6-b54d-7eecb83b0885.png)

Slider - Just a spatial node I'm using to contain the slider
Frame - A static-object model for the non-moving part of the slider
SliderOrigin - A spatial node to set the sliders "Zero" position and to rotate the slider movement to be in the correct orientation
InteractableSlider - An instance of the InteractableSlider. It sets its position and only slides along its X axis, which is why the SliderOrigin parent node rotates its X axis to be vertical
SliderBody - A static-object model for the moving part of the slider
HandleOrigin - A spatial node to set the relaxed/default grab location of the handle
InteractableHandle - An instance of the InteractableHandle. It tracks its position relative to the handle origin to move the slider
CollisionShape - The grab shape for grabbing the handle

**Comment by pietru2004** [comment]
Correct me If I see it wrong...

SO I would need to only copy "res://addons/godot-xr-tools/interactables/" to my project and copy/edit demo btns/sliders and in theory it could work. Correct?
+
I would need to place Credit line Like 

godot-xr-tools-interactables by Malcolmnixon under MIT License 
(without counting base XR Tools and addon licences)

**Comment by pietru2004** [comment]
Checked and it seams there in theory wouldn't be conflicts
![obraz](https://user-images.githubusercontent.com/51274570/156897113-b0f07fe0-34bd-43c1-a21b-f9c7f2dbf0d1.png)
